openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT  
security:
  - bearerAuth: []   
servers:
  - url: "http//localhost:5000"
paths:
  /api/auth/login:
    post:
      tags:
       - Device
      description: returns all registered devices
      operationId: getDevices
      parameters:
        - in: "query"
          name: "email"
          description: "Email"
          schema:
            type: string
            format: int32
        - in: "query"
          name: "Password"
          description: "Password"
          schema:
            type: "string"
            format: "int32"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: uri
                  example: 'http://localhost:5000'
  
